(("[INFO ]"    #XE2B0)
 ("[WARN ]"    #XE2B1)
 ("[PASS ]"    #XE2B2)
 ("[VERBOSE]"  #XE2B3)
 ("[KO]"       #XE2B4)
 ("[OK]"       #XE2B5)
 ("[PASS]"     #XE2B6)
 ("[ERROR]"    #XE2C0)
 ("[DEBUG]"    #XE2C1)
 ("[INFO]"     #XE2C2)
 ("[WARN]"     #XE2C3)
 ("[WARNING]"  #XE2C4)
 ("[ERR]"      #XE2C5)
 ("[FATAL]"    #XE2C6)
 ("[TRACE]"    #XE2C7)
 ("[FIXME]"    #XE2C8)
 ("[TODO]"     #XE2C9)
 ("[BUG]"      #XE2CA)
 ("[NOTE]"     #XE2CB)
 ("[HACK]"     #XE2CC)
 ("[MARK]"     #XE2CD)
 ("[FAIL]"     #XE2CE)
 ("# ERROR"    #XE2F0)
 ("# DEBUG"    #XE2F1)
 ("# INFO"     #XE2F2)
 ("# WARN"     #XE2F3)
 ("# WARNING"  #XE2F4)
 ("# ERR"      #XE2F5)
 ("# FATAL"    #XE2F6)
 ("# TRACE"    #XE2F7)
 ("# FIXME"    #XE2F8)
 ("# TODO"     #XE2F9)
 ("# BUG"      #XE2FA)
 ("# NOTE"     #XE2FB)
 ("# HACK"     #XE2FC)
 ("# MARK"     #XE2FD)
 ("# FAIL"     #XE2FE)
 ("// ERROR"   #XE2E0)
 ("// DEBUG"   #XE2E1)
 ("// INFO"    #XE2E2)
 ("// WARN"    #XE2E3)
 ("// WARNING" #XE2E4)
 ("// ERR"     #XE2E5)
 ("// FATAL"   #XE2E6)
 ("// TRACE"   #XE2E7)
 ("// FIXME"   #XE2E8)
 ("// TODO"    #XE2E9)
 ("// BUG"     #XE2EA)
 ("// NOTE"    #XE2EB)
 ("// HACK"    #XE2EC)
 ("// MARK"    #XE2ED)
 ("// FAIL"    #XE2EE))
